# Project to print letters as 5*7 blocks

print(" CCC    N   N")
print("C   C   NN  N")
print("C       N N N")
print("C       N  NN")
print("C       N   N")
print("C   C   N   N")
print(" CCC    N   N")


print("      *     *                    ")
print("                      *          ")
print("*         *                 *    ")
print("     *           *     *         ")
print("           HHHHHHH        *      ")
print(" *         HHHHHHH               ")
print("     *   HHHHHHHHHHH    *     *  ")
print("         *   @ @   *             ")
print("        *     ^     *            ")
print("  *       *       *         *    ")
print("         SSS * * S               ")
print("         * SSSSSSSS *            ")
print("       *      O   SS  *          ")
print("      *       O    S   *         ")
print("      *       O        *         ")
print("       *              *          ")
print("           *   *   *             ")
